version: '3'

services:
  traefik:
    image: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik-net
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    command: --docker \
             --docker.swarmMode \
             --docker.domain=$HOSTNAME \
             --docker.watch \
             --api \
             --entryPoints='Name:http Address::80' \
             --entryPoints='Name:https Address::443 TLS' \
             --defaultEntryPoints='http,https'
    deploy:
      labels:
        traefik.port: 8080
        traefik.frontend.rule: Host:$HOSTNAME
        traefik.docker.network: $TRAEFIK_NETWORK_NAME

networks:
  traefik-net:
    external:
      name: traefik-net
