version: "3"

networks:
  traefik:
    external:
      name: ${TRAEFIK_NETWORK}

services:
  traefik:
    image: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./config:/config
    env_file:
      - .env
    networks:
      - traefik
    ports:
      - 80:80
      - 443:443
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.middlewares=vault@file
      - traefik.http.routers.traefik.rule=Host(`${TRAEFIK_HOSTNAME}`)
      - traefik.http.services.traefik-service.loadbalancer.server.port=8080
